[package]
name = "typer"
version = "0.1.0"
authors = ["Krovspei Stepan <shtefanrpg@gmail.com>"]

[dependencies]
xml-rs = "0.8.0"
rusttype = "0.7.2"
image = "0.20.1"


[dev-dependencies]


[[example]]
name = "simple"

[profile.dev]
opt-level = 2